import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

const SEED_TEMPLATES = [
  // ─── QUICK QUOTE TEMPLATES ───────────────────────────────────────────────────
  {
    name: '10m3 Hardox Tipper Body',
    category: 'quick-quote',
    description: 'Standard 10m3 Hardox 500 tipper body. Includes Binotto 3190 hoist, Razor PVC/MESH electric tarp, V.Orlandi coupling, electric hand controller, split & supply hydraulic tank. Price fixed for standard fitment — minor dimensional adjustments to suit truck chassis at no extra cost.',
    imagePath: '/images/truck-bodies/hardox-tipper.jpg',
    configuration: {
      buildType: 'truck-body',
      templateType: 'quick-quote',
      material: 'Hardox 500',
      floorSheet: '6mm Hardox 500',
      sideSheet: '5mm Hardox 500',
      frontSheet: '5mm Hardox 500',
      tailgateSheet: '5mm Hardox 500',
      hoist: 'Binotto 3190',
      tarpSystem: 'Razor PVC/MESH Electric',
      coupling: 'V Orlandi',
      controls: 'Electric hand controller',
      hydraulics: 'Split & supply hydraulic tank',
      tailgateType: 'Single Piece Drop Down',
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      priceChangeItems: [
        'Different hoist model',
        'Bi-fold tailgate',
        'Manual tarp instead of electric',
        'Quarry spec width (2400mm)',
        'Material change (e.g. Bisalloy)',
      ],
      standardNotes: [
        'Dimensions may vary ±25mm to suit specific truck chassis at no extra cost',
        'Price based on standard fitment — major option changes quoted separately',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 45000,
    sortOrder: 1,
  },
  {
    name: 'Alloy Tipper Body',
    category: 'quick-quote',
    description: 'Standard alloy tipper truck body. Includes Razor PVC/MESH electric tarp and electric hand controller.',
    imagePath: '/images/truck-bodies/alloy-tipper.jpg',
    configuration: {
      buildType: 'truck-body',
      templateType: 'quick-quote',
      material: 'Aluminium',
      tarpSystem: 'Razor PVC/MESH Electric',
      controls: 'Electric hand controller',
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Dimensions may vary ±25mm to suit specific truck chassis at no extra cost',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 0,
    sortOrder: 6,
  },
  {
    name: 'Alloy Truck + 3 Axle Dog',
    category: 'quick-quote',
    description: 'Standard alloy tipper truck body + 3-axle SAF air ride dog trailer. Includes Razor PVC/MESH electric tarp on both truck and trailer.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      truckConfig: {
        material: 'Aluminium',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
      },
      trailerConfig: {
        trailerModel: 'DT-3 (3-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 3,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 0,
    sortOrder: 7,
  },
  {
    name: 'Alloy Truck + 4 Axle Dog 19m3',
    category: 'quick-quote',
    description: 'Standard 19m3 alloy tipper truck body + 4-axle SAF air ride dog trailer. Includes Razor PVC/MESH electric tarp on both truck and trailer. PBS rated 56.5T GCM.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      capacity: '19m3',
      pbsRating: '56.5T GCM',
      truckConfig: {
        material: 'Aluminium',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        price: 55000,
      },
      trailerConfig: {
        trailerModel: 'DT-4 (4-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 4,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
        price: 125000,
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
        'PBS compliant to 56.5T GCM',
      ],
    },
    basePrice: 180000,
    sortOrder: 8,
  },
  {
    name: 'Alloy Truck + 4 Axle Dog 20m3',
    category: 'quick-quote',
    description: 'Standard 20m3 alloy tipper truck body + 4-axle SAF air ride dog trailer. Includes Razor PVC/MESH electric tarp on both truck and trailer. PBS rated 57.5T GCM.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      capacity: '20m3',
      pbsRating: '57.5T GCM',
      truckConfig: {
        material: 'Aluminium',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        price: 55000,
      },
      trailerConfig: {
        trailerModel: 'DT-4 (4-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 4,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
        price: 126750,
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
        'PBS compliant to 57.5T GCM',
      ],
    },
    basePrice: 181750,
    sortOrder: 9,
  },
  {
    name: 'Alloy Truck + 5 Axle Dog',
    category: 'quick-quote',
    description: 'Standard alloy tipper truck body + 5-axle SAF air ride dog trailer. Includes Razor PVC/MESH electric tarp on both truck and trailer.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      truckConfig: {
        material: 'Aluminium',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
      },
      trailerConfig: {
        trailerModel: 'DT-5 (5-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 5,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 0,
    sortOrder: 10,
  },
  {
    name: 'Hardox Truck + 3 Axle Dog',
    category: 'quick-quote',
    description: 'Standard Hardox 500 tipper truck body + 3-axle SAF air ride dog trailer. Includes Razor PVC/MESH electric tarp on both truck and trailer.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      truckConfig: {
        material: 'Hardox 500',
        floorSheet: '6mm Hardox 500',
        sideSheet: '5mm Hardox 500',
        hoist: 'Binotto 3190',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        hydraulics: 'Split & supply hydraulic tank',
      },
      trailerConfig: {
        trailerModel: 'DT-3 (3-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 3,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 0,
    sortOrder: 7,
  },
  {
    name: 'Hardox Truck + 4 Axle Dog 19m3',
    category: 'quick-quote',
    description: 'Standard 19m3 Hardox 500 tipper truck body + 4-axle SAF air ride dog trailer. Includes Razor PVC/MESH electric tarp on both truck and trailer.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      capacity: '19m3',
      truckConfig: {
        material: 'Hardox 500',
        floorSheet: '6mm Hardox 500',
        sideSheet: '5mm Hardox 500',
        hoist: 'Binotto 3190',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        hydraulics: 'Split & supply hydraulic tank',
      },
      trailerConfig: {
        trailerModel: 'DT-4 (4-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 4,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 0,
    sortOrder: 8,
  },
  {
    name: 'Hardox Truck + 4 Axle Dog 20m3',
    category: 'quick-quote',
    description: 'Standard 20m3 Hardox 500 tipper truck body + 4-axle SAF air ride dog trailer. Includes Razor PVC/MESH electric tarp on both truck and trailer.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      capacity: '20m3',
      truckConfig: {
        material: 'Hardox 500',
        floorSheet: '6mm Hardox 500',
        sideSheet: '5mm Hardox 500',
        hoist: 'Binotto 3190',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        hydraulics: 'Split & supply hydraulic tank',
      },
      trailerConfig: {
        trailerModel: 'DT-4 (4-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 4,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 0,
    sortOrder: 9,
  },
  {
    name: 'Hardox Truck + 5 Axle Dog',
    category: 'quick-quote',
    description: 'Standard Hardox 500 tipper truck body + 5-axle SAF air ride dog trailer. Includes Razor PVC/MESH electric tarp on both truck and trailer.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      truckConfig: {
        material: 'Hardox 500',
        floorSheet: '6mm Hardox 500',
        sideSheet: '5mm Hardox 500',
        hoist: 'Binotto 3190',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        hydraulics: 'Split & supply hydraulic tank',
      },
      trailerConfig: {
        trailerModel: 'DT-5 (5-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 5,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 0,
    sortOrder: 10,
  },

  // ─── CONFIGURE BUILD TEMPLATES (starting points for custom builds) ───────────
  {
    name: 'Hardox Tipper Body — Custom',
    category: 'truck-body',
    description: 'Custom Hardox 500 tipper body for truck chassis. Configure dimensions, hoist, tarp, and options.',
    imagePath: '/images/truck-bodies/hardox-tipper.jpg',
    configuration: {
      buildType: 'truck-body',
      material: 'Hardox 500',
      floorSheet: '6mm Hardox 500',
      sideSheet: '5mm Hardox 500',
      frontSheet: '5mm Hardox 500',
      tailgateSheet: '5mm Hardox 500',
      hoist: 'Binotto 3190',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 1,
  },
  {
    name: 'Alloy Tipper Body — Custom',
    category: 'truck-body',
    description: 'Custom aluminium tipper body for truck chassis. Configure dimensions, hoist, tarp, and options.',
    imagePath: '/images/truck-bodies/alloy-tipper.jpg',
    configuration: {
      buildType: 'truck-body',
      material: 'Aluminium',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 2,
  },
  {
    name: '3-Axle Dog Trailer — Custom',
    category: 'trailer',
    description: 'DT-3 three axle dog trailer. Configure material, axles, suspension, tarp, and options.',
    imagePath: '/images/trailers/dog-trailer-3axle.png',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'DT-3 (3-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 1,
  },
  {
    name: '4-Axle Dog Trailer — Custom',
    category: 'trailer',
    description: 'DT-4 four axle dog trailer. Configure material, axles, suspension, tarp, and options.',
    imagePath: '/images/trailers/dog-trailer-4axle.jpg',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'DT-4 (4-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 2,
  },
  {
    name: '5-Axle Dog Trailer — Custom',
    category: 'trailer',
    description: 'DT-5 five axle dog trailer. Configure material, axles, suspension, tarp, and options.',
    imagePath: '/images/trailers/dog-trailer-5axle.jpg',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'DT-5 (5-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 3,
  },
  {
    name: '2-Axle Semi Trailer — Custom',
    category: 'trailer',
    description: 'ST-2 two axle semi trailer. Configure material, axles, suspension, tarp, and options.',
    imagePath: '/images/trailers/semi-trailer.jpg',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'ST-2 (2-Axle Semi)',
      trailerType: 'I Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 4,
  },
  {
    name: '3-Axle Semi Trailer — Custom',
    category: 'trailer',
    description: 'ST-3 three axle semi trailer. Configure material, axles, suspension, tarp, and options.',
    imagePath: '/images/trailers/semi-trailer.jpg',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'ST-3 (3-Axle Semi)',
      trailerType: 'I Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 5,
  },
  {
    name: 'Convertor Dolly — Custom',
    category: 'trailer',
    description: 'CD-2 or CD-3 convertor dolly.',
    imagePath: '/images/trailers/converter-dolly.jpg',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'CD-2 (2-Axle Convertor Dolly)',
      trailerType: 'Converter Dolly',
      material: 'Steel',
    },
    basePrice: 0,
    sortOrder: 6,
  },
]

export async function POST() {
  // Wipe all existing templates and re-seed from scratch (idempotent)
  await prisma.productTemplate.deleteMany()
  const results = await prisma.productTemplate.createMany({
    data: SEED_TEMPLATES.map((t) => ({
      ...t,
      configuration: t.configuration as any,
    })),
  })

  return NextResponse.json(
    { message: `Seeded ${results.count} templates (wiped previous)`, count: results.count },
    { status: 201 }
  )
}
