import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

const SEED_TEMPLATES = [
  // ─── QUICK QUOTE TEMPLATES ───────────────────────────────────────────────────
  {
    name: '10m3 Hardox Tipper Body',
    category: 'quick-quote',
    description: 'Standard 10m3 Hardox 500 tipper body. Approx 4660mm L × 1100mm H × 2400mm W. 6mm floor, 5mm sides. Includes Binotto 3190 hoist, Razor electric tarp, V.Orlandi coupling, electric hand controller, split & supply hydraulic tank, RHS subframe, VASS certification. Price fixed for standard fitment — minor dimensional adjustments to suit truck chassis at no extra cost.',
    imagePath: '/images/truck-bodies/hardox-tipper.jpg',
    configuration: {
      buildType: 'truck-body',
      templateType: 'quick-quote',
      material: 'Hardox 500',
      floorSheet: '6mm Hardox 500',
      sideSheet: '5mm Hardox 500',
      frontSheet: '5mm Hardox 500',
      tailgateSheet: '5mm Hardox 500',
      hoist: 'Binotto 3190',
      tarpSystem: 'Razor PVC/MESH Electric',
      coupling: 'V Orlandi',
      controls: 'Electric hand controller',
      hydraulics: 'Split & supply hydraulic tank',
      tailgateType: 'Single Piece Drop Down',
      capacity: '10m³',
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      priceChangeItems: [
        'Different hoist model',
        'Bi-fold tailgate',
        'Manual tarp instead of electric',
        'Quarry spec width (2400mm)',
        'Material change (e.g. Bisalloy)',
      ],
      standardNotes: [
        'Approx dimensions: 4660mm L × 1100mm H × 2400mm W (internal) — adjusted to suit chassis at no extra cost',
        '6mm Hardox 500 floor, 5mm Hardox 500 sides & ends',
        'RHS subframe w/ 50mm 4140 grade bar rear pivot and hardened 1020 grade steel bushes',
        'Includes VASS certification, LED lighting, mudflaps, anti-spray suppressant',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 45000,
    sortOrder: 1,
  },
  {
    name: 'Alloy Tipper Body',
    category: 'quick-quote',
    description: 'Standard aluminium tipper truck body. Approx 4600mm L × 1500mm H × 2400mm W quarry spec. 8mm alloy floor plate, 5mm sides, extruded corner posts & top rails. Includes Razor electric tarp, electric hand controller, RHS subframe, VASS certification. Price fixed for standard fitment.',
    imagePath: '/images/truck-bodies/alloy-tipper.jpg',
    configuration: {
      buildType: 'truck-body',
      templateType: 'quick-quote',
      material: 'Aluminium',
      floorSheet: '8mm Aluminium',
      sideSheet: '5mm Aluminium',
      tarpSystem: 'Razor PVC/MESH Electric',
      controls: 'Electric hand controller',
      capacity: 'approx 10m³',
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Approx dimensions: 4600mm L × 1500mm H × 2400mm W quarry spec — adjusted to suit chassis at no extra cost',
        '8mm aluminium floor plate welded to main beams, 5mm side walls, extruded top rails & splash guards',
        'Extruded aluminium corner posts, flat front sheet construction',
        'Includes VASS certification, LED lighting, mudflaps, anti-spray suppressant, shovel rack',
        'Coupling and hoist — specify at order. Binotto hoist available as addition.',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 55000,
    sortOrder: 6,
  },
  {
    name: 'Alloy Truck + 3 Axle Dog',
    category: 'quick-quote',
    description: 'Standard alloy tipper truck body + 3-axle SAF air ride alloy dog trailer. 8mm alloy floor, 5mm sides, extruded top rails. Strenx 700 chassis rails. Razor electric tarp on both, Binotto hoist, VASS certification.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      truckConfig: {
        material: 'Aluminium',
        floorSheet: '8mm Aluminium',
        sideSheet: '5mm Aluminium',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        price: 55500,
      },
      trailerConfig: {
        trailerModel: 'DT-3 (3-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 3,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
        price: 111000,
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Truck: 8mm alloy floor, 5mm side walls, extruded corner posts & top rails',
        'Trailer: 8mm alloy floor, 5mm sides, Strenx 700 chassis rails, Binotto hoist',
        'Drum or disc brake axles — specify at order (drum standard, disc upgrade additional)',
        'PBS certification available as addition',
        'Includes VASS certification on truck, LED lighting, mudflaps',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 166500,
    sortOrder: 7,
  },
  {
    name: 'Alloy Truck + 4 Axle Dog 19m3',
    category: 'quick-quote',
    description: 'Standard 19m3 alloy tipper truck body + 4-axle SAF air ride alloy dog trailer. Truck approx 4700mm L × 1500mm H. Trailer 7700mm L × 1500mm H, Strenx 700 chassis. 8mm alloy floor, 5mm sides, Binotto hoist, Razor electric tarp both. Tare approx 8,800kg combo. PBS rated 56.5T GCM.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      capacity: '19m3',
      pbsRating: '56.5T GCM',
      truckConfig: {
        material: 'Aluminium',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        price: 55000,
      },
      trailerConfig: {
        trailerModel: 'DT-4 (4-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 4,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
        price: 125000,
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Truck: 8mm alloy floor, 5mm sides, extruded corners & top rails, approx 4700mm L × 1500mm H × 2400mm W',
        'Trailer: 8mm alloy floor, 5mm sides, Strenx 700 chassis, approx 7700mm L × 1500mm H × 2400mm W',
        'Drum or disc brake axles — specify at order (disc upgrade is additional)',
        'PBS compliant to 56.5T GCM (included in this price)',
        '16 × Austyre 11R22.5 tubeless tyres, Alcoa outer wheels',
        'Includes VASS certification on truck, LED lighting, mudflaps',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 180000,
    sortOrder: 8,
  },
  {
    name: 'Alloy Truck + 4 Axle Dog 20m3',
    category: 'quick-quote',
    description: 'Standard 20m3 alloy tipper truck body + 4-axle SAF air ride alloy dog trailer. Truck approx 4700mm L × 1500mm H. Trailer 8300mm L × 1500mm H, Strenx 700 chassis. 8mm alloy floor, 5mm sides, Binotto hoist, Razor electric tarp both. 16 × Austyre 11R22.5 tyres, Alcoa Dura-Brite outer wheels. PBS rated 57.5T GCM.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      capacity: '20m3',
      pbsRating: '57.5T GCM',
      truckConfig: {
        material: 'Aluminium',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        price: 55000,
      },
      trailerConfig: {
        trailerModel: 'DT-4 (4-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 4,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
        price: 126750,
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
        'PBS compliant to 57.5T GCM',
      ],
    },
    basePrice: 181750,
    sortOrder: 9,
  },
  {
    name: 'Alloy Truck + 5 Axle Dog',
    category: 'quick-quote',
    description: 'Standard alloy tipper truck body + 5-axle SAF air ride dog trailer. Includes Razor PVC/MESH electric tarp on both truck and trailer.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      truckConfig: {
        material: 'Aluminium',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
      },
      trailerConfig: {
        trailerModel: 'DT-5 (5-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 5,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 0,
    sortOrder: 10,
  },
  {
    name: 'Hardox Truck + 3 Axle Dog',
    category: 'quick-quote',
    description: 'Standard Hardox 500 tipper truck body + 3-axle SAF air ride Hardox 500 dog trailer. Truck approx 4600mm L × 1100mm H. Trailer approx 6000mm L × 1100mm H. Includes Razor electric tarp on both, Binotto hoist, V.Orlandi coupling, VASS certification.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      truckConfig: {
        material: 'Hardox 500',
        floorSheet: '6mm Hardox 500',
        sideSheet: '5mm Hardox 500',
        hoist: 'Binotto 3190',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        hydraulics: 'Split & supply hydraulic tank',
        price: 47500,
      },
      trailerConfig: {
        trailerModel: 'DT-3 (3-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Hardox 500',
        axleMake: 'SAF',
        axleCount: 3,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
        price: 99500,
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Truck body: Hardox 500, approx 4600mm L × 1100mm H × 2400mm W',
        'Trailer: Hardox 500 body, Strenx 700 chassis rails, approx 6000mm L × 1100mm H × 2400mm W',
        'Drum or disc brake axles available — please specify at order (no price difference for drum)',
        'Trailer tare approx 6,800kg',
        'Includes VASS certification on truck, PBS certification available as addition',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 147000,
    sortOrder: 7,
  },
  {
    name: 'Hardox Truck + 4 Axle Dog 19m3',
    category: 'quick-quote',
    description: 'Standard 19m3 Hardox 500 tipper truck body + 4-axle SAF air ride Hardox 500 dog trailer. Truck approx 4700mm L × 1500mm H. Trailer approx 7700mm L × 1500mm H. Razor electric tarp both, Binotto hoist, VASS certification. PBS 48T available as option.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      capacity: '19m³',
      truckConfig: {
        material: 'Hardox 500',
        floorSheet: '6mm Hardox 500',
        sideSheet: '5mm Hardox 500',
        hoist: 'Binotto 3190',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        hydraulics: 'Split & supply hydraulic tank',
        price: 47500,
      },
      trailerConfig: {
        trailerModel: 'DT-4 (4-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Hardox 500',
        axleMake: 'SAF',
        axleCount: 4,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
        price: 112500,
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Truck: Hardox 500 body, approx 4700mm L × 1500mm H × 2400mm W',
        'Trailer: Hardox 500 body, Strenx 700 chassis, approx 7700mm L × 1500mm H × 2400mm W',
        'Drum or disc brake axles — please specify at order (disc upgrade is additional)',
        'PBS 48T certification available as addition',
        'Includes VASS certification on truck',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 160000,
    sortOrder: 8,
  },
  {
    name: 'Hardox Truck + 4 Axle Dog 20m3',
    category: 'quick-quote',
    description: 'Standard 20m3 Hardox 500 tipper truck body + 4-axle SAF air ride Hardox 500 dog trailer. Truck approx 4700mm L × 1500mm H. Trailer 8300mm L × 1100mm H, Strenx 700 chassis. Razor electric tarp both, Binotto hoist, VASS certification. PBS 57.5T available as option.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      capacity: '20m³',
      truckConfig: {
        material: 'Hardox 500',
        floorSheet: '6mm Hardox 500',
        sideSheet: '5mm Hardox 500',
        hoist: 'Binotto 3190',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        hydraulics: 'Split & supply hydraulic tank',
        price: 47500,
      },
      trailerConfig: {
        trailerModel: 'DT-4 (4-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Hardox 500',
        axleMake: 'SAF',
        axleCount: 4,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
        price: 115000,
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Truck: Hardox 500 body, approx 4700mm L × 1500mm H × 2400mm W',
        'Trailer: Hardox 500 body, Strenx 700 chassis, 8300mm L × 1100mm H × 2400mm W',
        'Drum or disc brake axles — please specify at order (disc upgrade is additional)',
        'PBS 57.5T / 20M certification available as addition',
        'Includes VASS certification on truck',
        '16 × Austyre 11R22.5 tubeless tyres, Alcoa polished outer wheels',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 162500,
    sortOrder: 9,
  },
  {
    name: 'Hardox Truck + 5 Axle Dog',
    category: 'quick-quote',
    description: 'Standard Hardox 500 tipper truck body + 5-axle SAF air ride dog trailer. Includes Razor PVC/MESH electric tarp on both truck and trailer.',
    imagePath: '/images/combos/alloy-truck-dog.jpg',
    configuration: {
      buildType: 'truck-and-trailer',
      templateType: 'quick-quote',
      truckConfig: {
        material: 'Hardox 500',
        floorSheet: '6mm Hardox 500',
        sideSheet: '5mm Hardox 500',
        hoist: 'Binotto 3190',
        tarpSystem: 'Razor PVC/MESH Electric',
        controls: 'Electric hand controller',
        hydraulics: 'Split & supply hydraulic tank',
      },
      trailerConfig: {
        trailerModel: 'DT-5 (5-Axle Dog)',
        trailerType: 'P Beam',
        material: 'Aluminium',
        axleMake: 'SAF',
        axleCount: 5,
        axleType: 'Drum or Disc (customer choice)',
        suspension: 'SAF Air Ride',
        tarpSystem: 'Razor PVC/MESH Electric',
      },
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Drum or disc brake axles available — please specify at order (no price difference)',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 0,
    sortOrder: 10,
  },

  // ─── TRAILER ONLY QUICK QUOTE TEMPLATES ─────────────────────────────────────
  {
    name: 'Alloy 4-Axle Dog Trailer 19m3',
    category: 'quick-quote',
    description: '4-axle alloy tipping dog trailer, 19m3. 7700mm L × 1500mm H × 2400mm W quarry spec. 8mm alloy floor, 5mm sides, Strenx 700 chassis, Binotto hoist, Razor electric tarp. SAF drum brakes, EBS, Alcoa wheels, 16 × Austyre 11R22.5 tyres. PBS 56.5T available.',
    imagePath: '/images/trailers/dog-trailer-4axle.jpg',
    configuration: {
      buildType: 'trailer',
      templateType: 'quick-quote',
      trailerModel: 'DT-4 (4-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Aluminium',
      capacity: '19m³',
      pbsRating: '56.5T GCM',
      axleMake: 'SAF',
      axleCount: 4,
      axleType: 'Drum or Disc (customer choice)',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Dimensions: 7700mm L × 1500mm H × 2400mm W quarry spec',
        '8mm alloy floor plate, 5mm side walls, Strenx 700 chassis rails',
        'Binotto 4-stage hoist, Razor electric tarp, SAF drum brakes with EBS',
        'Drum or disc brakes — specify at order (disc upgrade is additional)',
        'PBS 56.5T / 19M certification available as addition',
        '16 × Austyre 11R22.5 tubeless tyres, Alcoa Dura-Brite outer wheels',
        'Includes LED lighting, mudflaps, anti-spray suppressant, hubodometer',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order',
      ],
    },
    basePrice: 125000,
    sortOrder: 11,
  },
  {
    name: 'Alloy 4-Axle Dog Trailer 20m3',
    category: 'quick-quote',
    description: '4-axle alloy tipping dog trailer, 20m3. 8300mm L × 1500mm H × 2400mm W quarry spec. 8mm alloy floor, 5mm sides, Strenx 700 chassis, Binotto hoist, Razor electric tarp. SAF drum brakes, EBS, Alcoa wheels, 16 × Austyre 11R22.5 tyres. PBS 57.5T available.',
    imagePath: '/images/trailers/dog-trailer-4axle.jpg',
    configuration: {
      buildType: 'trailer',
      templateType: 'quick-quote',
      trailerModel: 'DT-4 (4-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Aluminium',
      capacity: '20m³',
      pbsRating: '57.5T GCM',
      axleMake: 'SAF',
      axleCount: 4,
      axleType: 'Drum or Disc (customer choice)',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Dimensions: 8300mm L × 1500mm H × 2400mm W quarry spec',
        '8mm alloy floor plate, 5mm side walls, Strenx 700 chassis rails',
        'Binotto 4-stage hoist, Razor electric tarp, SAF drum brakes with EBS',
        'Drum or disc brakes — specify at order (disc upgrade is additional)',
        'PBS 57.5T / 20M certification available as addition',
        '16 × Austyre 11R22.5 tubeless tyres, Alcoa Dura-Brite outer wheels',
        'Includes LED lighting, mudflaps, anti-spray suppressant, hubodometer',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order',
      ],
    },
    basePrice: 126750,
    sortOrder: 12,
  },
  {
    name: 'Hardox 3-Axle Dog Trailer',
    category: 'quick-quote',
    description: 'Hardox 500 3-axle tipping dog trailer. Approx 6000mm L × 1100mm H × 2400mm W. 6mm Hardox 500 floor, 5mm sides, Strenx 700 chassis. Binotto hoist, Razor electric tarp, SAF drum brakes, ADR EBS. Alcoa polished outer wheels, Austyre tyres. PBS available.',
    imagePath: '/images/trailers/dog-trailer-3axle.png',
    configuration: {
      buildType: 'trailer',
      templateType: 'quick-quote',
      trailerModel: 'DT-3 (3-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Hardox 500',
      axleMake: 'SAF',
      axleCount: 3,
      axleType: 'Drum or Disc (customer choice)',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Dimensions: approx 6000mm L × 1100mm H × 2400mm W',
        '6mm Hardox 500 floor, 5mm Hardox 500 sides & ends, Strenx 700 chassis',
        'Binotto hoist, Razor electric tarp, SAF drum brakes with ADR EBS',
        'Drum or disc brakes — specify at order (disc upgrade is additional)',
        'PBS certification available as addition',
        'Alcoa polished outer wheels, Austyre 11R22.5 tubeless tyres',
        'Includes LED lighting, mudflaps, anti-spray suppressant, hubodometer',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order',
      ],
    },
    basePrice: 98700,
    sortOrder: 13,
  },
  {
    name: 'Hardox 4-Axle Dog Trailer 20m3',
    category: 'quick-quote',
    description: 'Hardox 500 4-axle tipping dog trailer, 20m3. 8300mm L × 1100mm H × 2400mm W. 6mm Hardox 500 floor, 5mm sides, Strenx 700 chassis. Binotto 4-stage hoist, Razor electric tarp, SAF drum brakes, EBS, Alcoa wheels. PBS 57.5T available.',
    imagePath: '/images/trailers/hardox-dog-trailer-4axle.png',
    configuration: {
      buildType: 'trailer',
      templateType: 'quick-quote',
      trailerModel: 'DT-4 (4-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Hardox 500',
      capacity: '20m³',
      axleMake: 'SAF',
      axleCount: 4,
      axleType: 'Drum or Disc (customer choice)',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Dimensions: 8300mm L × 1100mm H × 2400mm W',
        '6mm Hardox 500 floor, 5mm Hardox 500 sides & ends, Strenx 700 chassis',
        'Binotto 4-stage hoist, Razor electric tarp, SAF drum brakes with ADR EBS',
        'Drum or disc brakes — specify at order (disc upgrade is additional)',
        'PBS 57.5T / 20M certification available as addition',
        '16 × Austyre 11R22.5 tubeless tyres, Alcoa Dura-Brite outer wheels',
        'Includes LED lighting, mudflaps, anti-spray suppressant, hubodometer',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order',
      ],
    },
    basePrice: 115000,
    sortOrder: 14,
  },

  {
    name: 'Alloy 3-Axle Dog Trailer',
    category: 'quick-quote',
    description: 'Alloy 3-axle tipping dog trailer. Approx 6000mm L × 1100mm H × 2400mm W. 6mm Hardox 500 floor, 5mm sides, Strenx 700 chassis. Binotto hoist, Razor electric tarp, SAF drum brakes, ADR EBS. Alcoa polished outer wheels, Austyre tyres. PBS available.',
    imagePath: '/images/trailers/dog-trailer-3axle.png',
    configuration: {
      buildType: 'trailer',
      templateType: 'quick-quote',
      trailerModel: 'DT-3 (3-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      axleCount: 3,
      axleType: 'Drum or Disc (customer choice)',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
      leadTimeWeeks: 5,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Dimensions: approx 6000mm L × 1100mm H × 2400mm W',
        '6mm Hardox 500 floor, 5mm sides, Strenx 700 chassis rails',
        'Binotto hoist, Razor electric tarp, SAF drum brakes with ADR EBS',
        'Drum or disc brakes — specify at order (disc upgrade is additional)',
        'PBS certification available as addition',
        'Alcoa polished outer wheels, Austyre 11R22.5 tubeless tyres',
        'Includes LED lighting, mudflaps, anti-spray suppressant, hubodometer',
        'Lead time 5 weeks from deposit',
        '30% deposit required to confirm order',
      ],
    },
    basePrice: 111000,
    sortOrder: 15,
  },

  {
    name: '3-Axle Tag Trailer',
    category: 'quick-quote',
    description: '3-axle tag trailer with beavertail and twin hydraulic ramps. 2480W × up to 8000mm flat deck + 1000mm beavertail. 5mm checkered plate floor, 8mm laser cut combing rails, SAF Intra disc brakes, air bag suspension, ADR 3-axle EBS. Twin ramps 900×2800mm. Alcoa wheels, Austyre 255R70×22.5 low profile tyres.',
    imagePath: '/images/trailers/tag-trailer-3axle.jpg',
    configuration: {
      buildType: 'trailer',
      templateType: 'quick-quote',
      trailerModel: 'TT-3 (3-Axle Tag)',
      trailerType: 'Tag',
      material: 'Steel',
      deckWidth: '2480',
      flatDeckLength: 'Up to 8000',
      beavertailLength: 'Approx 1000',
      deckHeight: 'Approx 1040',
      drawbarLength: 'Approx 1600 (built-in frame)',
      floor: '5mm checkered plate',
      combingRails: '8mm flush laser cut',
      headboard: '250mm front headboard',
      chainPoints: '8 × in-floor tie down/chain points',
      hammerWell: '2000mm × 750mm × 450mm',
      rampType: 'Twin Hydraulic Ramps',
      rampWidth: '900',
      rampLength: '2800',
      hydraulics: 'Powerpack with Redarc Battery Charging System (batteries hidden)',
      anderson: 'Anderson plug and associated wiring for charging system',
      lighting: 'Approx 9 × Hella LED side lights, Jumbo rear LED tail lights',
      coupling: 'Pintle hook/ring feeder or Bartlett ball tow hitch',
      drawbarLeg: 'Hydraulic drawbar landing leg',
      airFittings: 'Duo-matic air fittings to suit truck',
      safetyChains: '16mm safety chains (or to suit existing chain lugs)',
      axleMake: 'SAF',
      axleCount: 3,
      axleSeries: 'SAF Intra series',
      axleType: 'Disc brakes',
      suspension: 'Air bag suspension',
      braking: 'ADR approved 3-axle EBS (multi-volt)',
      tyres: '255R70×22.5 low profile — Austyres',
      wheels: 'Alcoa polished outer, Alcoa machined inner',
      spareWheel: 'Spare wheel and tyre on wound-up rack',
      paint: 'Sandblast frame, PPG 2K paint systems — colour match to cab',
      mudflaps: 'Complete set of YLZ mudflaps',
      leadTimeWeeks: 8,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        'Flat deck up to 8000mm + approx 1000mm beavertail, 2480mm wide, deck height approx 1040mm',
        'Built-in frame drawbar approx 1600mm, hydraulic drawbar landing leg',
        '5mm checkered plate floor, 8mm flush laser cut combing rails, 250mm front headboard',
        'Heavy gauge cross members and chassis frame throughout',
        '8 × in-floor tie down/chain points, hammer well 2000 × 750 × 450mm',
        'Twin hydraulic ramps 900mm × 2800mm with laser cut profiling and internal structure',
        'Powerpack with Redarc Battery Charging System (batteries hidden), Anderson plug and wiring',
        'Approx 9 × Hella LED side lights, Jumbo rear LED tail lights',
        'Pintle hook/ring feeder or Bartlett ball tow hitch (specify at order)',
        'Duo-matic air fittings, 16mm safety chains (or to suit existing chain lugs on truck)',
        'SAF Intra series 3-axle disc brakes, air bag suspension',
        'ADR approved 3-axle EBS braking system (multi-volt)',
        '255R70×22.5 low profile Austyre tyres, Alcoa polished outer, Alcoa machined inner wheels',
        'Wheel alignment, spare wheel and tyre on wound-up rack',
        'Sandblasted frame, PPG 2K paint systems — colour match to cab',
        'Complete set of YLZ mudflaps',
        'Subject to final customer request, engineering and design approvals',
        'Lead time 8 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 68500,
    sortOrder: 16,
  },

  {
    name: 'Beavertail with Twin Ramps',
    category: 'quick-quote',
    description: 'Standard beavertail body with twin ramps. 2470W × 8500L (7000mm flat deck, 1200mm tail). 5mm checkered plate floor, profile laser cut side rails, 400mm cross-members. Hydraulic power pack 3000 PSI. Twin ramps 800mm × 2700mm, 12T rated. Stabiliser legs, rope rails, LED lights, PPG 2-pack paint.',
    imagePath: '/images/trailers/beavertail.jpg',
    configuration: {
      buildType: 'beavertail',
      templateType: 'quick-quote',
      btDeckWidth: '2470', btDeckLength: '8500', btFlatDeckLength: '7000',
      btTailLength: '1200', btTailAngle: '15', btRampExtension: '300',
      btRampType: 'Twin Ramps', btRampWidth: '800', btRampActualLength: '2700', btRampCapacity: '12T',
      btFloorPlate: '5mm checkered plate', btCrossMembers: '400mm',
      btHydraulics: 'Hydraulic Power pack 3000 PSI, double controls with push button hand control and key switch isolator',
      btStabiliserLegs: '2 x stabilising legs rated at 10T',
      btChainPoints: '4 x key chain points per side',
      btToolbox: '900 x 450 x 450',
      btShovelRacks: '2 x shovel racks to headboard behind cabin',
      btLights: 'Jumbo LED tail lights and side marker lamps',
      btPaint: 'Etch primed and painted with PPG 2pack systems. Colour match to cab.',
      btEngineeringNote: 'subject to final engineering and approval',
      leadTimeWeeks: 6,
      paymentTerms: '30% deposit or dealer PO',
      standardNotes: [
        '2470W × 8500L beavertail body (7000mm flat deck, 1200mm tail, 300mm ramp extension)',
        '5mm checkered plate floor fully welded, profile laser cut side rails, 400mm cross-members',
        'Hydraulic power pack 3000 PSI with dual controls and key switch isolator',
        'Twin ramps 800mm × 2700mm, 5mm checkered plate, rated at 12T capacity',
        '2 × stabilising legs 10T rated, laser cut rope rails, 4 × key chain points per side',
        'Jumbo LED tail lights and side marker lamps',
        'Etch primed and painted with PPG 2-pack systems, colour match to cab',
        'Lead time 6 weeks from deposit',
        '30% deposit required to confirm order, or dealer purchase order',
      ],
    },
    basePrice: 45455,
    sortOrder: 16,
  },

  // ─── CONFIGURE BUILD TEMPLATES (starting points for custom builds) ───────────
  {
    name: 'Hardox Tipper Body — Custom',
    category: 'truck-body',
    description: 'Custom Hardox 500 tipper body for truck chassis. Configure dimensions, hoist, tarp, and options.',
    imagePath: '/images/truck-bodies/hardox-tipper.jpg',
    configuration: {
      buildType: 'truck-body',
      material: 'Hardox 500',
      floorSheet: '6mm Hardox 500',
      sideSheet: '5mm Hardox 500',
      frontSheet: '5mm Hardox 500',
      tailgateSheet: '5mm Hardox 500',
      hoist: 'Binotto 3190',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 1,
  },
  {
    name: 'Alloy Tipper Body — Custom',
    category: 'truck-body',
    description: 'Custom aluminium tipper body for truck chassis. Configure dimensions, hoist, tarp, and options.',
    imagePath: '/images/truck-bodies/alloy-tipper.jpg',
    configuration: {
      buildType: 'truck-body',
      material: 'Aluminium',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 2,
  },
  {
    name: '3-Axle Dog Trailer — Custom',
    category: 'trailer',
    description: 'DT-3 three axle dog trailer. Configure material, axles, suspension, tarp, and options.',
    imagePath: '/images/trailers/dog-trailer-3axle.png',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'DT-3 (3-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 1,
  },
  {
    name: '4-Axle Dog Trailer — Custom',
    category: 'trailer',
    description: 'DT-4 four axle dog trailer. Configure material, axles, suspension, tarp, and options.',
    imagePath: '/images/trailers/dog-trailer-4axle.jpg',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'DT-4 (4-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 2,
  },
  {
    name: '5-Axle Dog Trailer — Custom',
    category: 'trailer',
    description: 'DT-5 five axle dog trailer. Configure material, axles, suspension, tarp, and options.',
    imagePath: '/images/trailers/dog-trailer-5axle.jpg',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'DT-5 (5-Axle Dog)',
      trailerType: 'P Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 3,
  },
  {
    name: '2-Axle Semi Trailer — Custom',
    category: 'trailer',
    description: 'ST-2 two axle semi trailer. Configure material, axles, suspension, tarp, and options.',
    imagePath: '/images/trailers/semi-trailer.jpg',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'ST-2 (2-Axle Semi)',
      trailerType: 'I Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 4,
  },
  {
    name: '3-Axle Semi Trailer — Custom',
    category: 'trailer',
    description: 'ST-3 three axle semi trailer. Configure material, axles, suspension, tarp, and options.',
    imagePath: '/images/trailers/semi-trailer.jpg',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'ST-3 (3-Axle Semi)',
      trailerType: 'I Beam',
      material: 'Aluminium',
      axleMake: 'SAF',
      suspension: 'SAF Air Ride',
      tarpSystem: 'Razor PVC/MESH Electric',
    },
    basePrice: 0,
    sortOrder: 5,
  },
  {
    name: 'Convertor Dolly — Custom',
    category: 'trailer',
    description: 'CD-2 or CD-3 convertor dolly.',
    imagePath: '/images/trailers/converter-dolly.jpg',
    configuration: {
      buildType: 'trailer',
      trailerModel: 'CD-2 (2-Axle Convertor Dolly)',
      trailerType: 'Converter Dolly',
      material: 'Steel',
    },
    basePrice: 0,
    sortOrder: 6,
  },
]

export async function POST() {
  // Wipe all existing templates and re-seed from scratch (idempotent)
  await prisma.productTemplate.deleteMany()
  const results = await prisma.productTemplate.createMany({
    data: SEED_TEMPLATES.map((t) => ({
      ...t,
      configuration: t.configuration as any,
    })),
  })

  return NextResponse.json(
    { message: `Seeded ${results.count} templates (wiped previous)`, count: results.count },
    { status: 201 }
  )
}
